---
type: map
mapping:
  access:
    type: map
    mapping:
      mode:
        enum:
          - public
          - private
        type: str
      session:
        type: map
        mapping:
          secret:
            type: str
          expires:
            type: int
          httponly:
            type: int
          secure:
            type: int
          domain:
            type: str
          path:
            type: str
      users:
        type: seq
        sequence:
          - type: map
            mapping:
              username:
                type: str
              password:
                type: str
              hashing:
                type: str
              salt:
                type: str
  listen:
    type: str
  pool:
    type: map
    mapping:
      workers:
        type: int
      mode:
        enum:
          - inproc
          - fork
          - detach
        type: str
  projects:
    required: 1
    type: seq
    sequence:
    - mapping:
        id:
          type: str
        existing_rev:
          enum:
            - build
            - ignore
            - error
        webhooks:
          type: seq
          sequence:
          - type: map
            mapping:
              id:
                type: str
                required: 1
              cgi:
                type: str
                required: 1
        build:
          type: seq
          sequence:
          - type: str
        post:
          type: seq
          sequence:
          - type: str
      type: map
  workers:
    type: map
    mapping:
      language:
        type: int
      stopwaitsecs:
        type: int
